jamie-password: ENC[AES256_GCM,data:bujPAUvTkNWIGZdSPs77fkEAFUF1qltf/i8DzFZVZDVXOcd/xNDHJ4fyarZuvUu2tqWmGjBXF8nU1fqiAIN+7jZMZ9CJUCazcg==,iv:1WCasa+A8ZmLnrT5u5y67f0J8uNPmMXIgWs/bk4Qqms=,tag:wLlLKTXfTefnao0BBWaNOg==,type:str]
calendar-personal: ENC[AES256_GCM,data:2mBAP23SvBn02/RbTU/mnytLSqLWAm0rGZn/FoYkvZ1ytuyd3Tppoz6ACVwqaRrkwPRweh096HgzA03BcN2LvP5oHtT0LQPvsRgtJxVTRVYohHAb2FVubE+Hud4cYoz8mG54EQAxd3H3pu043ZXDnt6KAEdhPd+2hPeWCeEZPjfgTCppJpoDRt7ISMpiappjqQhbN9C1QTi9fC9QGvMgtGx+Xfh32n6Ke1mLYUSs90bCP99PXm/Y3nKTiJmhKm/bgpCXoms7+W4NLOEK/j78PJ+i3Z1s4A7uVtPOo7L2ROQV5qMWwalubjPu/F7qZnXtuOUAPrkc7w==,iv:i2rX8Hn0uCIA+ivah4CB2F8MUtBsCq4UBVCjOKJI87I=,tag:YXLM1rF+Bhw0bYepeZA5SA==,type:str]
calendar-work: ENC[AES256_GCM,data:ufoh1h4S9rsq9cK+FgfOhf1TV/p2gyho+G9CTcjeWFzSDKxDdedAL2K04XC8QlgroYvtlG3WaDkZhCeVIGNwQPTQerNT0RedM6hiz+k+jXzl+TCqSZtefyvymkRTTNDU/gmvvP6ta93VaTTr53qXuqZDCLkUbN6A/26xPnJ80f2xyGhpD+LO2CwXxpZXrP3iY7deTzKA/8jYCc4ZxSUYO0h2ejkuOtrcmcuz1/2Tl6m0kD4vUJWdvm1mN4V/0gZRSGDtQqAiazTIuVnYLFEGNIFNi2gIGiX99HYDjr4YAWLVbZT9z1P4eUpBQXEFvEhKOQFE7TBSvA==,iv:ZoBxCfgRNwPV/4JaJvkIxtfZe+VHCuraFHfQ0WY243I=,tag:4FaIPT1tkpODntjG69r4tg==,type:str]
wakapi-env: ENC[AES256_GCM,data:ULH2Z/bQ7EpPVvGEcz/7ifoT/lJ2k6M45rGaTpCWpfCzGl2xrPWUl9CQQ3Mkv+mSAHXc3kBXh6coYuj2yuWioj9dGw==,iv:Q6twhRWBpzY33TN48UG9Gyzji7wP4ZSUOSHz2Mukfmk=,tag:4hlchSr8r2jNSpX5Ugbfww==,type:str]
wakapi-key: ENC[AES256_GCM,data:kez3wvH4G/iunLdknBh5O5PKyqvl4oU3sU7+KOqMAvLj8VeV,iv:gDnpZFibixQtS65tQl80XmoCnkmvutOD/yC0p+Wg4E4=,tag:3LK6ojShpGQ0y8GXlzPFow==,type:str]
sops:
    age:
        - recipient: age1689hns6xrgas8fc8dk809m48qeetlfvu9au3942ewhyqe7kyye3qdvzdtc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNWtoNWY1Z3B3UjJqNlVl
            R3VVNURXbFpIVXNFSE5TYnRNaE53SnExMkJzCkNNdE9ydk1nWTZjeEtURzYzOTdr
            SEp5c1BqYnNxQ3djVC9ZdFFtTkExc3MKLS0tIDRBMHVZWnNhMTllSWNZRFZQZi9n
            czJaVGJiN3FKK2RRbGZDaGxOakZidmcKe4r/vakBPU/oOk6prC4DuYLgNkt5vEDa
            xS9Vi2HBCGP1qJxDrxLvlz+IHHzC2rArd3LKM2XhiA0Q2Pdvbgn+Dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14zp3stx7nnwqkze488ckacz6h9u4ed3p8v92jyvv0lxhnw6qxp6qnn28a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRjlqS1hvSlBYN2s3V2Rn
            cDF4eUZRTEFKeEhWZkRLY3ZKcHhOMGZHWUdRClVJbjB2cFNDb2Z6clZpSEdJRmFz
            ZkpmT2dlV2t6bTJPUjJzbWZmMmQ4ZDQKLS0tIFQ0ZVRja0pWNUwwWG1qbktRSncr
            eVVDcWk1bHh5ZHdtTUFaMkIzRndIYlEK7V7YpPaiSWHo3twVLG2mkYJ8rp1RzPXx
            CyqeWUgWaZnNSFQ8G4/KObliKj3a0AFmO6eE1pZL8o13SFe2st3FMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1salqmxagycvhs8unnddzwyg3aptn3tp9g7g7g5p25w3urw5kxvds72swg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcFJyVGZrSkU0K0cwWFRB
            UmY4ZzdXaG5BdDN5clk5RTVPTmNTeVQ4TlFBCmM0QVRqdHE4YUtIWWZVUitKTExq
            eWZhNlg1ZDBCcVorM2pKYkROUDlSb0EKLS0tIGpzMU5FQklSVWZvekdtOXBiRzlG
            ekNKZFVKSzdxNFcxVXJMQ1ZCT3dOdHcKgaTAeQiFakh+NjvJl4audp8puVCECzEB
            IG68Tb/1aIrUyy6IKfZ8GdC5OMkcKpFwG61Ub8yaBJFkDIGHj4eYSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:39:30Z"
    mac: ENC[AES256_GCM,data:1LUuAqi4XNAOHEBnv8UYFGTlFYw7i/n5+j7Cc8mqH3s+uJjUuRxJ3V6z+Zip1bEyz8h+AuSBKWjesxqibN3v+r2yVxwRzhN0vKpswb1XXr0VG2If6/vHCcDVeWJXrlfFc4WxbtFBXAStwd5TSa51VTppvnkXOLvMgrgAQDptcpM=,iv:tqfLL9/JeLt7RVneRzGq4NcQzBhx+CggbujUVGKi/p4=,tag:v+eWcy7Q0zuy/rqxsF1eIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
