wakapi-env: ENC[AES256_GCM,data:crbsg9rO3S4u9YgBhhRNqg12z/1kRwlmCd2RzGAWmqXSI5j3mOgiyca0EMprB4hGxgTYzXzuyps0rJBimKHAZustRJ6gHqsneZ5JSZskdY9PbXZBkuAM08kunlExLrJ1+xr+ZTQPI7ZuUqQ/NF6hIOqdrCIphNIKHv4+UJBRviwoh6G84VN+stpLlVvzhIA1SjKQe/RzwNjvm3sbS2Guz6hjANbgA0Chc68GMYVhWPSrL5py5jBTsV+Of80CY8lOVCv4GX713iWL2XY4/OWu2UXMfKCRpfl+zDy2rHhpSRiZMN9E0F/RsJ32D+/rEqyH1a6wXlRH2GOBk+wKVtbV3eyXTxBzNy40XkAfPDP174I6wLCD1USwl5zTRxKFxcfqyR+tv/Lno7T+YCqSKOdp0tp73netkKWZvX+MtqKnwC/R+/2VJzwAjfp2XBjFgfP7o2GrNFIfhqypyBWpRZv6UsJmfljwwsP16pATr3A6Gav2sdwCHyRB+WDv/bqzPHFrL7WcaLqdWlCKR2fREMvYTgPzzwY6EdGDC5KhGkvU7gDNO7IjJuaHbkVN2wvN8TEolt5wSAI0D6ORUp1MzHyLO19UjTWEUNW58rSYcSvqo2s4TVCLz20gmPBsO/QtEcB5k8Pd4kFVt0ub+jdn9zVg4rY7/P6zH7Ue/jlJFoz0BidBU0vmsP7xsmgUSV6skrdY,iv:HlgR03Nl9UgdZWmbmAbHtwTthwgTdmjW9ddEiih2vg0=,tag:gw2tg7AJONAkkPfBtgWehA==,type:str]
wakapi-key: ENC[AES256_GCM,data:Ow0mIU1UT4TnEAkRAY+3VnCpfu5Rf1pkts2DU3DSS7I30db3,iv:gDnpZFibixQtS65tQl80XmoCnkmvutOD/yC0p+Wg4E4=,tag:YJ+WfMnWQfQZJc6ritsnnQ==,type:str]
pocketid-encryption-key: ENC[AES256_GCM,data:REZQSIOQ8NNUCYjP/2OfxIuYLgVy6m1NnatHXaL0mUrh8z/ik8l8mNm88pU=,iv:seshbXDNRkubmcEO7plXuUCnuCLWn0AFaYp22jZuqJk=,tag:ejke0oY128ktHcFeD9zwqw==,type:str]
pocketid-smtp-pass: ENC[AES256_GCM,data:1C5uL+EYTKlHGWQN15RO6g==,iv:uOHmo+M+W6eq/UbKCVmM629p6R1tQ99ktodXc6PUV2g=,tag:ZDj8zO51PKYz0DvD7XWe1g==,type:str]
pocketid-karakeep-secret: ENC[AES256_GCM,data:+Vtxq4m9gx0XGaPyLv5ssd5uC2RZFieJZO5VZyRQu8w=,iv:/8nC6j2WpWSw6i1MvwxBGcZABcXp+Tx/OlI2wHGDG8k=,tag:vQmwVQedmJUqMhYRv8RuIw==,type:str]
pocketid-drasl-secret: ENC[AES256_GCM,data:Cfz2ambe5t9CHdFi7sn3Rp4unO92SWodsZIWOzwc13k=,iv:2CfkgFA+7eWaZZHXJu7fdbJbTDvJDW5NrbONlGUoK8Q=,tag:2RhI6IF4EFd8Zg70L8qtCw==,type:str]
pocketid-miniflux-secret: ENC[AES256_GCM,data:/zrR2IMlQhXeOxmzSFLb/Dr8fFc6L/LVLU0pwg45Xmc=,iv:5/biDCR4Ex6jDaqOGs05dabxww8ys9xx8/xQV6vRIyM=,tag:wNa+22MX8zuPX0j+WC1A1w==,type:str]
tailscale-auth-key: ENC[AES256_GCM,data:o/ZOx50JXhE5GUsdsHI8f+fO7zISxxvNyJ0rLTRtZVty5uREzECUFR+SDbWAfUpnfh5VlCBQ/pZPskrkkA==,iv:QGETS/1jF+12IXy5ymrHPRJSaqR2XkiNeHv7HQ4W9T4=,tag:SYc0IOl6PTzibuTRijTtdA==,type:str]
mollysocket-env: ENC[AES256_GCM,data:ojNOkMHfIn3Jts50Wx8etOxw2hse4vUXMLw3P8OgsRTW/LvyvpXcV9BHsqVebnThqoGvCH1aysR+cdsZTI1N5YYIl/ysHYscw4gXEvkJx5DhIhGX+aHVaRZT6TZ0T3CUsewsjJTVYJoj2JN/TjRH4WwNZjty1CuwCnhRUKS3zQ==,iv:miMC1TABmbq056cmKWhGtoWrUdatH3r2ykBuNK7SoSQ=,tag:P+ngxA2yRcdC/25i4erUKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZlJrSjNjemVvSzFyanYr
            SkF1dmpzTW5MWFdIVjVkaTZ3dUxJYVFuUFdJCnJWK3A4VkhHNlhrQWFqL21kUWVQ
            aExBNXROOS9xOSthWFNNalhXeThRencKLS0tICtlZmdFSW92WG55dTloLzUrZC9Z
            RWsySnN5ZUFaakpQTENDV2MxR1lhZW8K8KU9RUEJtl1vGm0rP8heyhqnY21qqY1h
            BV7oFHoCKyyLG6Zk30EobNUq7opOL42+GcsjSuTipWo34ip7qG5FaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1689hns6xrgas8fc8dk809m48qeetlfvu9au3942ewhyqe7kyye3qdvzdtc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVGc3aVFqaUtUWGJqWG9o
            ZUJJSFcxanJTd21RaDRYcitZZW1tUHpNOFNrCjJPOHYvUzdBM1BOOVFkRGRkWkJO
            MFptcXZYVVh2enIwSytUTjhoTjFISTgKLS0tIFJqQzNKU3p6Mkw0MmlHM0pqR2dS
            R0NyNmUvL2ducVVYK0MvUm1Uc2VZdk0K0kSwIWxtovCgXtvJmGArAIYrhGs5opK0
            cwfNi9JJl4UcTzcvZSz34Q8dBA6Q48OXLHoHh7d1EwFX8RUCISrFyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14zp3stx7nnwqkze488ckacz6h9u4ed3p8v92jyvv0lxhnw6qxp6qnn28a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTDY5T3VBLzFpWDgveXll
            ZXM2ZnFvMmNsOXZmcVZKWFBvT1JvMmhYMzNjClpTRnFteHR6MmtCU0VQVE54WHBu
            NTMvdk9QQmV5Ri9GWnJRWENacFo4a1UKLS0tIFBMdFFlZ2NwZFByeUJEZnI1MENP
            NzIwS2ZnTk5Wc2Roalh2bmpRa1FHZEEKFur5jcFRhloL9OtsZIvcig7L5e3kfEus
            Mfs8mpZ8h/9rQhmAS9RKNS2bzT+bOJuQ6kASE7pJ7j1fjqpHqC0SXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1salqmxagycvhs8unnddzwyg3aptn3tp9g7g7g5p25w3urw5kxvds72swg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYUZlcXg3S3BjK1NodVRH
            OGVtanBWOHdwSURCRC9zSUhSWGhka3BHTUM0CnJOTUtsWFFiT3VmRGs3NDRBWGti
            dFgrcGwwTDU3TUMyQnZhejhzeU96OUkKLS0tIGxPUUxwS0pRWnR1aEFQT3JQMmc3
            Z2dQKzFsbURLUzg2d2MrdDBrT0RadWMKAX1r2Od2U10z1620VqZd/QUV51krv9nz
            lZqf/EiTtyDBdA3YDt2wMDBNgo7owwAiFxdp7PYYmq2xpY4AqVv7uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18ewzvkpaj65c8c8jr5e90sw9dwrnu56vznf3exgydd65edpd4gnsqxsmx6
    lastmodified: "2026-07-20T16:18:56Z"
    mac: ENC[AES256_GCM,data:nOq9DtLYZTsZ6EMgp1b4MAZZqPP5RUCnHEu/rh4H5NaE0R8q5rKyzf3Sj9tu2KkOzuVEIuUtViMMTDqcssSAnMiH7icJS2b0EjjF/UUF3b0LQTCYrGMdiguPh7So9/Nc+DnGi+kNw7Yv5np0hW8M/PXN8RCV3ucoWipSAsQUsnA=,iv:+I8wBuFH82LgAl6jYS1XvU+Y/OwJpFv99B6Ca06p2KE=,tag:BsGFfvFFD1bLuti/nHa9gQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
