# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "macos-26-20260219-2aa12422";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/macos-26-20260219-2aa12422/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-U1oEOvBHBtJEcQWeZHRb/IDWYXraLuo0NdxWINwPUxg=";
    };
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PDF0/wObw4nIsSBeXVYLsloXOiphXCgIdsrNcVXguKs=";
    };
    date = "2026-05-03";
  };
  equibop-bin = {
    pname = "equibop-bin";
    version = "3.2.0";
    src = fetchurl {
      url = "https://github.com/Equicord/Equibop/releases/download/v3.2.0/Equibop-3.2.0-universal.dmg";
      sha256 = "sha256-NqLmoO4mhk9hPrELIc3lLwgxLNj2wvr0Y1GLk4VSf3g=";
    };
  };
  helium-appimage = {
    pname = "helium-appimage";
    version = "0.12.3.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.12.3.1/helium-0.12.3.1-x86_64.AppImage";
      sha256 = "sha256-VnOhzhAulvFNBB/0AD1d+K/TzfFL9Zwtk/vcm5vWl+I=";
    };
  };
  helium-dmg = {
    pname = "helium-dmg";
    version = "0.12.3.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.12.3.1/helium_0.12.3.1_arm64-macos.dmg";
      sha256 = "sha256-BrbexBlCQh9htQEy4Wiul/oNSn2MVERoqpLT8VRLENM=";
    };
  };
  hyprland-preview-share-picker = {
    pname = "hyprland-preview-share-picker";
    version = "344394a8669fb82ff2744d2780327dd402ffb76a";
    src = fetchFromGitHub {
      owner = "WhySoBad";
      repo = "hyprland-preview-share-picker";
      rev = "344394a8669fb82ff2744d2780327dd402ffb76a";
      fetchSubmodules = true;
      sha256 = "sha256-dreIL3+GfrTxzN5ZoQvLvEc8qFlTs/qwQZjPFJS1eJQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-dreIL3+GfrTxzN5ZoQvLvEc8qFlTs_qwQZjPFJS1eJQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-03-04";
  };
  liga-sf-mono-nerd-font = {
    pname = "liga-sf-mono-nerd-font";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  owo-sh = {
    pname = "owo-sh";
    version = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
    src = fetchgit {
      url = "https://owo.codes/whats-this/owo.sh.git";
      rev = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vwvUiM7mOixyNERjITwcS90jz15QFkwxCEtYzqm+hdg=";
    };
    date = "2023-04-10";
  };
  pearcleaner-bin = {
    pname = "pearcleaner-bin";
    version = "5.4.3";
    src = fetchurl {
      url = "https://github.com/alienator88/Pearcleaner/releases/download/5.4.3/Pearcleaner.dmg";
      sha256 = "sha256-+hTyxyRhCbM3OzRiqoFxel+iSIr6QcpcWoc4TIh0mqY=";
    };
  };
  proton-cachyos_x86_64_v3 = {
    pname = "proton-cachyos_x86_64_v3";
    version = "cachyos-11.0-20260506-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260506-slr/proton-cachyos-11.0-20260506-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-c7Zj46wubq3ZYqganMx4TfP4OgMiEBKoDRuR3KJMSY0=";
    };
  };
  protonpass-bin = {
    pname = "protonpass-bin";
    version = "1.36.1";
    src = fetchurl {
      url = "https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_1.36.1.dmg";
      sha256 = "sha256-JKm5DhIZLj2XXuxWKo48VY4onRypouIJUVV9IK/wJGE=";
    };
  };
  protonvpn-bin = {
    pname = "protonvpn-bin";
    version = "6.1.0";
    src = fetchurl {
      url = "https://vpn.protondownload.com/download/macos/6.1.0/ProtonVPN_mac_v6.1.0.dmg";
      sha256 = "sha256-u/J32eIgpQkvF87j4Lc3IKT0YkJHTx4JauL6TsXg/ls=";
    };
  };
  spotiflac-cli = {
    pname = "spotiflac-cli";
    version = "780b8c9ae2f7ba8b3d7a8aae811db6ecb5ca52e3";
    src = fetchFromGitHub {
      owner = "Nizarberyan";
      repo = "SpotiFLAC";
      rev = "780b8c9ae2f7ba8b3d7a8aae811db6ecb5ca52e3";
      fetchSubmodules = false;
      sha256 = "sha256-pjDD7FZbuok4ccBN7sGWb0KzMFi4ZfsEcYmM1pWYyGU=";
    };
    date = "2026-03-12";
  };
  swipeaerospace-bin = {
    pname = "swipeaerospace-bin";
    version = "0.3.0";
    src = fetchurl {
      url = "https://github.com/MediosZ/SwipeAeroSpace/releases/download/0.3.0/SwipeAeroSpace.zip";
      sha256 = "sha256-koHHD9ofObiwNFtCV5bkNhHH29vGzTcvCMUTDOjzWKc=";
    };
  };
}
