# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  ...
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "macos-26-20260218-4989e498";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/macos-26-20260218-4989e498/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-49g+MqagqHjejBaw7qCSWhNb5CdVfsRyHS4dUg+ZxEo=";
    };
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "7725e097895102ca2949c7a553b54dca0b2e2667";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "7725e097895102ca2949c7a553b54dca0b2e2667";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lOw77YOBM6HNuWcLL4Qugn+vr4RxMKV8FgXqFlnyLIo=";
    };
    date = "2026-02-17";
  };
  equibop-bin = {
    pname = "equibop-bin";
    version = "3.1.8";
    src = fetchurl {
      url = "https://github.com/Equicord/Equibop/releases/download/v3.1.8/Equibop-3.1.8-universal.dmg";
      sha256 = "sha256-fmucyEnVkh08EfmRPBOOH805/XJboke5y3njWXN1pYc=";
    };
  };
  helium-dmg = {
    pname = "helium-dmg";
    version = "0.9.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.9.2.1/helium_0.9.2.1_arm64-macos.dmg";
      sha256 = "sha256-DtfBq0sX/ylRsCml3YdUvUYUq4PX5raAtWowx2XJcqk=";
    };
  };
  helium-tarball = {
    pname = "helium-tarball";
    version = "0.9.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.9.2.1/helium-0.9.2.1-x86_64_linux.tar.xz";
      sha256 = "sha256-wDHs/FEoOkYUjKPUrM9QAPwsqNvURJhlP/RZteLL2gA=";
    };
  };
  liga-sf-mono-nerd-font = {
    pname = "liga-sf-mono-nerd-font";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  morewaita-icon-theme = {
    pname = "morewaita-icon-theme";
    version = "v49";
    src = fetchgit {
      url = "https://github.com/somepaulo/MoreWaita.git";
      rev = "v49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GUvEMVGFbGA0Vjvl22xHAtELKasT2V0vcQkkpytQPuE=";
    };
  };
  owo-sh = {
    pname = "owo-sh";
    version = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
    src = fetchgit {
      url = "https://owo.codes/whats-this/owo.sh.git";
      rev = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vwvUiM7mOixyNERjITwcS90jz15QFkwxCEtYzqm+hdg=";
    };
    date = "2023-04-10";
  };
  pearcleaner-bin = {
    pname = "pearcleaner-bin";
    version = "5.4.3";
    src = fetchurl {
      url = "https://github.com/alienator88/Pearcleaner/releases/download/5.4.3/Pearcleaner.dmg";
      sha256 = "sha256-+hTyxyRhCbM3OzRiqoFxel+iSIr6QcpcWoc4TIh0mqY=";
    };
  };
  proton-cachyos_x86_64_v3 = {
    pname = "proton-cachyos_x86_64_v3";
    version = "cachyos-10.0-20260207-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260207-slr/proton-cachyos-10.0-20260207-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-76iQrZKa2ysCDKV4jysWqthaiKMfjGWQR7r6IwilktI=";
    };
  };
  proton-cachyos_x86_64_v4 = {
    pname = "proton-cachyos_x86_64_v4";
    version = "cachyos-10.0-20260207-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260207-slr/proton-cachyos-10.0-20260207-slr-x86_64_v4.tar.xz";
      sha256 = "sha256-/GkMdSjP3DkbYjvvDEZvI2Na4WFW27zVwxkf9sLQj80=";
    };
  };
  protonpass-bin = {
    pname = "protonpass-bin";
    version = "1.34.2";
    src = fetchurl {
      url = "https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_1.34.2.dmg";
      sha256 = "sha256-oo02IYOKZEsr0+4zimSFkutTGuS63ZvMZTeUTapZrVw=";
    };
  };
  protonvpn-bin = {
    pname = "protonvpn-bin";
    version = "6.1.0";
    src = fetchurl {
      url = "https://vpn.protondownload.com/download/macos/6.1.0/ProtonVPN_mac_v6.1.0.dmg";
      sha256 = "sha256-u/J32eIgpQkvF87j4Lc3IKT0YkJHTx4JauL6TsXg/ls=";
    };
  };
  swipeaerospace-bin = {
    pname = "swipeaerospace-bin";
    version = "0.2.5";
    src = fetchurl {
      url = "https://github.com/MediosZ/SwipeAeroSpace/releases/download/0.2.5/SwipeAeroSpace.zip";
      sha256 = "sha256-v3zjXCxCS2Vsjqoc+vYvbN3hiBKy2Jh+uIrG2ZSPmn0=";
    };
  };
}
