[apple-emoji]
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji-Linux.ttf"
src.github = "samuelngs/apple-emoji-linux"

[proton-cachyos_x86_64_v3]
fetch.url = "https://github.com/CachyOS/proton-cachyos/releases/download/$ver/proton-$ver-x86_64_v3.tar.xz"
src.github = "CachyOS/proton-cachyos"
